import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/utils/redux/reduxProvider";
import { ToastContainer } from "react-toastify";
import Topbar from "@/components/Topbar/Topbar";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import CartSidebar from "@/components/Products/CartSidebar/CartSidebar";
import Sidebar from "@/components/Sidebar/Sidebar";
import { ScrollTop } from "@/components/ScrollTop/ScrollTop";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Al-Shafi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${montserrat.variable} antialiased`}>
        <ReduxProvider>
          <>
            <Topbar />
            <Navbar />
          </>
          <main className=" md:min-h-[calc(100vh-665px)]">
            {children}
            <ScrollTop />
            <CartSidebar />
            <Sidebar />
          </main>

          <Footer />
        </ReduxProvider>
        <ToastContainer position="top-center" />
      </body>
    </html>
  );
}
